// <auto-generated />
using System;
using KundenManagment1.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KundenManagment1.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KundenManagment1.Shared.Dept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KundeKdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KundeKdId");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("KundenManagment1.Shared.Kunde", b =>
                {
                    b.Property<int>("KdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KdId"), 1L, 1);

                    b.Property<string>("KdAdresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KdAlter")
                        .HasColumnType("int");

                    b.Property<string>("KdImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KdId");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("KundenManagment1.Shared.Dept", b =>
                {
                    b.HasOne("KundenManagment1.Shared.Kunde", null)
                        .WithMany("Dept")
                        .HasForeignKey("KundeKdId");
                });

            modelBuilder.Entity("KundenManagment1.Shared.Kunde", b =>
                {
                    b.Navigation("Dept");
                });
#pragma warning restore 612, 618
        }
    }
}
